apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: us.gcr.io/ridesharing-dev-312709/bookings
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: carpooling
            - name: MONGO_URI
              value: 'mongodb://bookings-mongo-srv:27017/bookings'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: rides-srv
spec:
  selector:
    app: rides
  ports:
    - name: rides
      protocol: TCP
      port: 3000
      targetPort: 3000
