apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiry-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiry
  template:
    metadata:
      labels:
        app: expiry
    spec:
      containers:
        - name: expiry
          image: us.gcr.io/ridesharing-dev-312709/expiry
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: carpooling
            - name: REDIS_HOST
              value: expiry-redis-srv
