apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rides
  template:
    metadata:
      labels:
        app: rides
    spec:
      containers:
        - name: rides
          image: us.gcr.io/ridesharing-dev-312709/rides
          env:
            - name: MONGO_URI
              value: 'mongodb://rides-mongo-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: rides-srv
spec:
  selector:
    app: rides
  ports:
    - name: rides
      protocol: TCP
      port: 3000
      targetPort: 3000
